name: tagpr
on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: Songmu/tagpr@587e213186455e82540ef27b7db4f862d0a2da41 # v1.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
